FROM tomcat:latest
WORKDIR /
# RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41-deployer.tar.gz
# RUN tar -xvzf apa*
# RUN mv apache-tomcat-9.0.4.tar.gz tomcat
COPY target/*.war webapps
CMD bin/catalina.sh run
