server:
  port: 9191
  
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/person/**

